### PR TITLE
TSP function with meander to get more contrast in the plot

### PR DESCRIPTION
**Pull request by sergio-daniels**
Hello Brandon,
I would like to commit the feature to draw a more contrast riche TSP plot where the lines between the TSP cities are drawn by a meander depending on the radius of the city. More details on http://4um.gocupi.com/t/draw-tsp-with-different-line-thickness/61
Kind regards
Sergio

### CODE REVIEW

**Comment by jromero** [comment]
@sergio-daniels Not speaking for @brandonagr, I would like to see this feature incorporated but I see some file changes that probably shouldn't be there and that might be the reason why it's not such a simple merge. for example:
* README.md
* gocupi.go lines 7-8, 370

**Comment by brandonagr** [comment]
Sorry, must have not been paying attention to the github notification emails, I will try to merge this later today

**Comment by brandonagr** [comment]
Hmm, only realized after that deleting the Linus.svg from the commit into my master still left it in history, so a pull will take a bit longer than normal now, not sure if its possible to remove a file from history.
Do you have any other smaller svg files that are good to show features of meanderStipple?

**Comment by sergio-daniels** [comment]
Hi Brandon, i will commit a smaler svg file later.

**Comment by sergio-daniels** [comment]
Hi Brandon,
I did a new pull request with a smaler SVG example.

**Pull request merged**
